services:
  backend:
    build:
      context: ./backend
    container_name: todo-backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - todo_backend_data:/data
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: todo-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  todo_backend_data:  # Объявление тома (Docker создаст его автоматически)
