services:
  backend:
    build:
      context: ./backend
    container_name: todo-backend
    expose:
      - "8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      target: static-export
    container_name: todo-frontend
    volumes:
      - frontend_data:/srv/frontend
    depends_on:
      - backend

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    command: ["caddy", "run", "--config", "/etc/caddy-prod/Caddyfile", "--adapter", "caddyfile"]
    volumes:
      - ./Caddyfile.prod:/etc/caddy-prod/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - frontend_data:/srv/frontend
    depends_on:
      - frontend
      - backend

volumes:
  todo_backend_data:
  frontend_data:
  caddy_data:
  caddy_config: